### ISSUE TITLE
[MaterialAutoCompleteTextView] error: cannot find symbol

### ISSUE THREAD

**Issue by VincentJoshuaET** [material-components/material-components-android#1211]
**Description:** Cannot build project after updating to 1.2.0-alpha06

**Android API version:** 29

**Material Library version:** 1.2.0-alpha06

Reverting to 1.2.0-alpha05 fixes the problem.

**Comment by VincentJoshuaET** [comment]
A workaround is to use AutoCompleteTextView instead of MaterialAutoCompleteTextView.
