### ISSUE TITLE
[TabLayout] Binary incompatible change in OnTabSelectedListener between 1.0.0 and 1.1.0-rc1

### ISSUE THREAD

**Issue by evant** [material-components/material-components-android#903]
Description: There appears to be an binary incompatible change with OnTabSelectedListener between 1.0.0 and 1.1.0-rc1 causing a runtime crash when using a lib compiled with the previous version on the later one.

- Expected behavior: A lib compiled against 1.0.0 will continue to work with 1.1.0.

- Source code:

The lib has a class: `Foo implements OnTabSelectedListener` and is compiled against 1.0.0
The app uses version 1.1.0-rc1

Expected: The app doesn't crash
Actual: The app crashes with

java.lang.IncompatibleClassChangeError: Class 'Foo' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener' in call to 'void com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener.onTabUnselected(com.google.android.material.tabs.TabLayout$Tab)' (declaration of 'com.google.android.material.tabs.TabLayout$1' appears in /data/app/app/base.apk)

- Android API version: N/A

- Device: N/A

**Comment by cketcham** [comment]
looks like the binary incompatibility might have been introduced by 2966cfb15f78e7197b67c1305cffe6c6f84b6af8 and 6f653a5af1093778a5bb15777a6018eee6c528e1

**Comment by evant** [comment]
Hm, just tried checking out that commit and I'm still seeing the issue.

It looks like in version 1.0.0, `OnTabSelectedListener` extended `BaseOnTabSelectedListener` and is linked against the version of `addOnTabSelectedListener` that takes `BaseOnTabSelectedListener`. In 1.1.0, `OnTabSelectedListener` no longer extends `BaseOnTabSelectedListener` so it breaks.

**Comment by pekingme** [comment]
Sorry to hear it still causing the issue, @evant. Could you provide more context about how to reproduce this? We'd like to fix this with a repro sample to confirm. Some information like this might be helpful.
- What is this library? Is it public, so that we can use to reproduce the bug?
- How do you use this library / what methods in the library is called?
- How are these methods implemented?

**Comment by evant** [comment]
- The library is not public but I think I can provide a sample repo.
- The library provides it's own ui which includes some tabs.
- It is calling `addOnTabSelectedListener` with a class that implements `OnTabSelectedListener`.

**Comment by evant** [comment]
Create a sample repo https://github.com/evant/material-tab-compat-issue

**Comment by dsn5ft** [comment]
@evant can you verify that https://github.com/material-components/material-components-android/commit/3cd591fd71d90e5a357a5ee5549ad36f9c08fdf2 fixes the issue?

**Comment by evant** [comment]
It does!
