### ISSUE TITLE
[Color] Error Attr. color not found

### ISSUE THREAD

**Issue by HanzoDev1375** [material-components/material-components-android#4817]
``` Task :app:compileArm64ReleaseJavaWithJavac
/storage/emulated/0/AndroidIDEProjects/Ghost-web-ide2/app/src/main/java/com/github/barteksc/pdfviewer/scroll/DefaultScrollHandle.java:25: error: cannot find symbol
import static com.google.android.material.R.attr.colorPrimary;
^
  symbol:   static colorPrimary
  location: class attr
/storage/emulated/0/AndroidIDEProjects/Ghost-web-ide2/app/src/main/java/com/github/barteksc/pdfviewer/scroll/DefaultScrollHandle.java:57: error: cannot find symbol
        setTextColor(MaterialColors.getColor(textView, colorPrimary));
                                                       ^
  symbol:   variable colorPrimary
  location: class DefaultScrollHandle
/storage/emulated/0/AndroidIDEProjects/Ghost-web-ide2/app/src/main/java/com/github/barteksc/pdfviewer/scroll/DefaultScrollHandle.java:90: error: cannot find symbol
        shaps.setStroke(2, ColorStateList.valueOf(MaterialColors.getColor(getContext(), colorPrimary, 0)));
                                                                                        ^
  symbol:   variable colorPrimary
  location: class DefaultScrollHandle
/storage/emulated/0/AndroidIDEProjects/Ghost-web-ide2/app/src/main/java/ir/ninjacoder/ghostide/activities/JsonViewerActivity.java:66: error: cannot find symbol
        go.setValueTextColor(MaterialColors.getColor(go, colorPrimary));
                                                         ^
  symbol:   variable colorPrimary
  location: class JsonViewerActivity
/storage/emulated/0/AndroidIDEProjects/Ghost-web-ide2/app/src/main/java/ir/ninjacoder/ghostide/activities/JsonViewerActivity.java:69: error: cannot find symbol
        go.setValueNumberColor(MaterialColors.getColor(go, colorError));
                                                           ^
  symbol:   variable colorError
  location: class JsonViewerActivity
/storage/emulated/0/AndroidIDEProjects/Ghost-web-ide2/app/src/main/java/ir/ninjacoder/ghostide/tasks/app/ProgressDialogCompat.java:37: warning: [dep-ann] deprecated item is not annotated with @Deprecated
public class ProgressDialogCompat extends AlertDialog {
       ^
/storage/emulated/0/AndroidIDEProjects/Ghost-web-ide2/app/src/main/java/ir/ninjacoder/ghostide/utils/ObjectUtils.java:87: error: cannot find symbol
  public static int colorAccent = R.attr.colorAccent;
                                        ^
  symbol:   variable colorAccent
  location: class attr
/storage/emulated/0/AndroidIDEProjects/Ghost-web-ide2/app/src/main/java/ir/ninjacoder/ghostide/utils/ObjectUtils.java:90: error: cannot find symbol
  public static int ColorNormal = R.attr.colorControlNormal;
                                        ^
  symbol:   variable colorControlNormal
  location: class attr
/storage/emulated/0/AndroidIDEProjects/Ghost-web-ide2/app/src/main/java/ir/ninjacoder/ghostide/utils/ObjectUtils.java:91: error: cannot find symbol
  public static int ColorAConNormal = R.attr.colorControlActivated;
                                            ^
  symbol:   variable colorControlActivated
  location: class attr
/storage/emulated/0/AndroidIDEProjects/Ghost-web-ide2/app/src/main/java/ir/ninjacoder/ghostide/utils/ObjectUtils.java:383: error: cannot find symbol
    int colorPrimary = R.attr.colorPrimary;
                             ^
  symbol:   variable colorPrimary
  location: class attr
/storage/emulated/0/AndroidIDEProjects/Ghost-web-ide2/app/src/main/java/ir/ninjacoder/ghostide/utils/ObjectUtils.java:503: error: cannot find symbol
    int colorPrimary = R.attr.colorPrimary;
                             ^
  symbol:   variable colorPrimary
  location: class attr
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
10 errors
1 warning
````
hi im using version 1.14.0-alpha01 
color not found
or see error 
https://github.com/HanzoDev1375/Ghostide/actions/runs/15615615651

**Comment by HanzoDev1375** [comment]
> https://github.com/HanzoDev1375/Ghostide is quite a large repo. Do you have a min repro sample? Does the same code work using 1.13 but seeing the errors in 1.14?

Hello and politeness, I tested it in several projects. Unfortunately, only version 14 has a problem. We tested version 13, it has no problems and it works well.

**Comment by pekingme** [comment]
@dsn5ft Do we have a doc or instruction about how the R file should be imported after 1.14? From the error above, it seems that all shown attributes are from the system or appcompat. I guess it's related to the resources (or R) package change recently.

**Comment by dsn5ft** [comment]
`android.nonTransitiveRClass=false` should let you not worry about the R class paths, but I'm not sure there's a way to have `com.google.android.material.R.attr.colorPrimary` work. It looks like the majority of your errors are for unqualified R references, like `R.attr.colorControlActivated`. So the simplest way to fix this would probably be to set `android.nonTransitiveRClass=false`, then references like `R.attr.colorControlActivated` should be fixed. And any like `com.google.android.material.R.attr.colorPrimary` can be updated to just `R.attr.colorPrimary`.
